version: '3.4'

services:

  dump1090:
    build: .
    links:
      - postgis
    environment:
      - DUMP1090_PORT
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PW
      - POSTGRES_DB
      - PYTHONPATH
    depends_on:
      - postgis

  postgis:
    image: mdillon/postgis
    ports:
      - "25432:5432"
    volumes:
      - dump1090:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  postgis-backup:
    build: postgis-backup
    depends_on:
     - postgis
    environment:
      - PGHOST
      - PGPORT
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_BUCKET
      - S3_HOST
      - CRON_SCHEDULE
    volumes:
      - postgis-backup:/backups

volumes:
  dump1090:
    name: dump1090
  postgis-backup:
    name: postgis-backup